### PR TITLE
Added required libs + headers from DirectX SDK

### PR DESCRIPTION
**Pull request by only-a-ptr**
RoR uses OGRE 1.9 which requires 'Microsoft DirectX SDK (June 2010)' installed.
However, this SDK has known installation issues and may break dev environment
in more than one way. Furthermore, all DirectX versions up to 11 are officially
obsoleted by Microsoft, the functionality is now part of Windows SDK.

Reading:
* https://blogs.msdn.microsoft.com/chuckw/2011/12/09/known-issue-directx-sdk-june-2010-setup-and-the-s1023-error/
* https://blogs.msdn.microsoft.com/chuckw/2013/08/20/living-without-d3dx/
* https://blogs.msdn.microsoft.com/chuckw/2015/08/05/where-is-the-directx-sdk-2015-edition/
* https://blogs.msdn.microsoft.com/chuckw/2015/03/23/the-zombie-directx-sdk/

This package contains Dx9 headers/binaries not included in Windows SDK, as
detailed in the "Zombie DirectX SDK" article.

The subdirectory 'License Agreements' is copied verbatim from the SDK.
Please see the included documents for more details.

**PS**: Is it a good idea to check in Microsoft's libs+headers into our deps? It surely isn't, but forcing developers to instal broken and huge ~600MB legacy SDK to get ~6.5MB of libs+headers is even worse. Also, it's quite temporary, because OGRE-2.1 migration is totally happening this year.

### CODE REVIEW

**Comment by AnotherFoxGuy** [comment]
Maybe it is a better idea to create a new GitHub repo for the Directx-SDK and clone it when building then include the SDK in this repo

**Comment by only-a-ptr** [comment]
@AnotherFoxGuy Maybe, but IMO we already have a bit too many repos, let's not make it worse.

The only reason to separate out the DxSDK deps I can think of would be legal - that way, we wouldn't 'taint' our deps repo with microsoft binaries. But since the ["zombie dxsdk" article](https://blogs.msdn.microsoft.com/chuckw/2015/03/23/the-zombie-directx-sdk/) says it's actually a widespread practice and Microsoft apparently doesn't punish this, I wouldn't worry. In the worst case, if we got legally nagged to remove the libs from all Git history, we can just rebase them out.

**Comment by only-a-ptr** [comment]
Apparently AppVeyor build fails because building takes too long. The log ends abruptly in the middle of compiling MyGUI. The limit seems to be exactly 1 hour.

**Comment by Speciesx** [comment]
@only-a-ptr 
Build without errors.
tested with VS 2017.

**Comment by AnotherFoxGuy** [comment]
Builds without problems 👍

**Pull request merged**
